var username1 = "Nida";
console.log(username1);
var username2 = "NidaFatima";
console.log(username2);
var address = "Garden";
console.log(address);
var city = "Karachi";
console.log(city);
var age = 20;
console.log(age);
var engage = false;
console.log(engage);
var favorite_holybook = "Quran Majeed";
console.log(favorite_holybook);
var Education = "intermidiate of commerce";
console.log(Education);
var favoriteColor = "Blue";
console.log(favoriteColor);
var favoriteDish = "Biryani";
console.log(favoriteDish);
var dream = "Touching Kaba";
console.log(dream);
var Hobbies = "Outing";
console.log(Hobbies);
var favorite_Cricketer = "Babar Azam";
console.log(favorite_Cricketer);
var interest = "Coding";
console.log(interest);
var Bestfriend = "Sonia";
console.log(Bestfriend);
var favorite_Sir = "Haseeb";
console.log(favorite_Sir);
var favorite_app = "instagram";
console.log(favorite_app);
var myschoolName = "Haseeb Public School";
console.log(myschoolName);
var goodbye = "false";
console.log(goodbye);
